/**
 * The MIT License
 * Copyright (c) 2025 Benoit Chatain Lacelle - SOLVEN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.solven.adhoc.pivotable.webflux.app;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springframework.beans.factory.NoSuchBeanDefinitionException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;
import org.springframework.core.env.Environment;
import org.springframework.core.env.Profiles;
import org.springframework.security.oauth2.client.registration.InMemoryClientRegistrationRepository;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.junit.jupiter.SpringExtension;

import eu.solven.adhoc.app.IPivotableSpringProfiles;
import eu.solven.adhoc.table.sql.AdhocJooqHelper;
import lombok.extern.slf4j.Slf4j;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = { PivotableServerWebfluxApplication.class },
		webEnvironment = SpringBootTest.WebEnvironment.MOCK,
		properties = { IPivotableSpringProfiles.P_CONFIG_IMPORT,

				"adhoc.pivotable.oauth2.issuer-base-url" + "=someUnittestIssuerBaseUrl",
				// Generated by PivotableResourceServerConfiguration
				"adhoc.pivotable.oauth2.signing-key"
						+ "={\"kty\":\"oct\",\"kid\":\"8cd35fd9-ec4a-4e6c-8f18-ad8e1e20074e\",\"k\":\"9tQsw3lbu_YZHZ-XqcQEz475CQQHEAzQRmXrIqu092w\",\"alg\":\"HS256\",\"iat\":1770918823}" })
@ActiveProfiles({
		// Simulate a prdmode (i.e. minimal) profile
		IPivotableSpringProfiles.P_PRDMODE,
		// Need to activate inmemory to store users
		IPivotableSpringProfiles.P_INMEMORY })
@Slf4j
public class TestPivotableServerWebfluxApplicationNoOAuth2 implements IPivotableSpringProfiles {
	static {
		AdhocJooqHelper.disableBanners();
	}

	@Autowired
	ApplicationContext appContext;
	@Autowired
	Environment env;

	@Test
	public void testSpringProfiles() {
		log.info("startupDate: {}", appContext.getStartupDate());

		Assertions.assertThat(env.acceptsProfiles(Profiles.of(IPivotableSpringProfiles.P_INMEMORY))).isTrue();
	}

	@Test
	public void testClientRegistrations() {
		// In prdmode, there is no default oauth2 registration
		Assertions.assertThatThrownBy(() -> appContext.getBean(InMemoryClientRegistrationRepository.class))
				.isInstanceOf(NoSuchBeanDefinitionException.class);
	}
}
