/**
 * The MIT License
 * Copyright (c) 2026 Benoit Chatain Lacelle - SOLVEN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.solven.adhoc.engine.tabular.splitter.merger;

import java.util.Set;

import com.google.common.collect.ImmutableSet;
import com.google.common.collect.LinkedHashMultimap;
import com.google.common.collect.Multimaps;
import com.google.common.collect.Sets;

import eu.solven.adhoc.engine.step.TableQueryStep;
import eu.solven.adhoc.engine.tabular.optimizer.GraphHelpers;
import eu.solven.adhoc.engine.tabular.optimizer.IAdhocDag;
import eu.solven.adhoc.filter.FilterHelpers;
import eu.solven.adhoc.filter.ISliceFilter;
import eu.solven.adhoc.filter.OrFilter;
import eu.solven.adhoc.filter.editor.SimpleFilterEditor;
import eu.solven.adhoc.filter.optimizer.IFilterOptimizer;
import eu.solven.adhoc.query.cube.IGroupBy;
import eu.solven.adhoc.util.AdhocFactoriesUnsafe;
import lombok.Builder;
import lombok.Builder.Default;
import lombok.NonNull;

/**
 * Will generate a minimal number of {@link TableQueryStep} while not merging any `GROUP BY`. Typically, `GROUP BY
 * (a,b)` and `GROUP BY (a,c)` is not merged into `GROUP BY (a,b,c)`.
 * 
 * However, filters can be merged as in `FILTER a1 GROUP BY (a,b)` and `GROUP BY (a)` can be merged into `GROUP BY
 * (a,b)`.
 * 
 * @author Benoit Lacelle
 */
@Deprecated(
		since = "This looks inefficient. May do better job one `UNION ALL` is fully supported (by JootTableQueryFactory)")
@Builder
public class MergeInducersStrictGroupBy implements IMergeInducers {
	@Default
	@NonNull
	protected final IFilterOptimizer filterOptimizer =
			AdhocFactoriesUnsafe.factories.getFilterOptimizerFactory().makeOptimizer();

	public static IMergeInducers.IMergeInducersFactory makeFactory() {
		return (stripperFactory,
				filterOptimizer) -> MergeInducersStrictGroupBy.builder().filterOptimizer(filterOptimizer).build();
	}

	/**
	 * Add inducer step when multiple existing step can be generated by a single step with an {@link OrFilter}. It
	 * requires all filtered columns to be available in the {@link IGroupBy} to enabling splitting the merge
	 * {@link OrFilter}.
	 * 
	 * @param steps
	 * @return
	 */
	// `FILTER a1&b1 GROUP BY (d)` and `FILTER a1&b2 GROUP BY (d)` are not mergeable as d can not split b1 and b2
	// `FILTER a1&b1 GROUP BY (b)` and `FILTER a1&b2 GROUP BY (b)` are mergeable as a1 is common
	// `FILTER a1&b1 GROUP BY (b)` and `FILTER a1&b2 GROUP BY (b)` and `FILTER e1` should not prevent the first 2 steps
	// to be merged
	@Override
	public IAdhocDag<TableQueryStep> mergeInducers(TableQueryStep contextualAggregator, Set<TableQueryStep> steps) {
		// induceWithOr: we may receive steps which can efficiently be merged together (e.g. `FILTER a1` and `FILTER a1`
		// can be merged into `FILTER a1 OR a2`)

		LinkedHashMultimap<TableQueryStep, TableQueryStep> mergingToSteps = steps.stream()
				.collect(Multimaps.toMultimap(this::stepForMergingFilter, s -> s, LinkedHashMultimap::create));

		mergeGroups(mergingToSteps);

		IAdhocDag<TableQueryStep> inducedToInducer = GraphHelpers.makeGraph();

		Multimaps.asMap(mergingToSteps).forEach((group, mergeableSteps) -> {
			if (mergeableSteps.size() < 2) {
				// nothing to merge
				return;
			}

			ImmutableSet<ISliceFilter> filters =
					mergeableSteps.stream().map(TableQueryStep::getFilter).collect(ImmutableSet.toImmutableSet());

			TableQueryStep merged = TableQueryStep.edit(group).filter(filterOptimizer.or(filters, false)).build();

			inducedToInducer.addVertex(merged);

			mergeableSteps.forEach(mergeableStep -> {
				inducedToInducer.addVertex(mergeableStep);
				inducedToInducer.addEdge(mergeableStep, merged);
			});
		});

		return inducedToInducer;
	}

	/**
	 * Enable a custom implementation to merge some groupes together.
	 * 
	 * @param mergingToSteps
	 */
	protected void mergeGroups(LinkedHashMultimap<TableQueryStep, TableQueryStep> mergingToSteps) {
		// Some implementation may be willing to merge some of these groups
	}

	protected TableQueryStep stepForMergingFilter(TableQueryStep step) {
		// columns which are filtered
		Set<String> filteredColumns = FilterHelpers.getFilteredColumns(step.getFilter());
		// columns which are filtered but not in groupBy
		Set<String> filteredNotGroupedBy = Sets.difference(filteredColumns, step.getGroupBy().getGroupedByColumns());

		// Given filter can not be inferred from slice
		ISliceFilter filterNotInGroupBy = SimpleFilterEditor.retainsColumns(step.getFilter(), filteredNotGroupedBy);

		return step.toBuilder().filter(filterNotInGroupBy).build();
	}
}
