/**
 * The MIT License
 * Copyright (c) 2026 Benoit Chatain Lacelle - SOLVEN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.solven.adhoc.engine.tabular.optimizer;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.common.collect.ImmutableSet;
import com.google.common.util.concurrent.AtomicLongMap;

import eu.solven.adhoc.column.ReferencedColumn;
import eu.solven.adhoc.filter.FilterBuilder;
import eu.solven.adhoc.filter.FilterHelpers;
import eu.solven.adhoc.filter.ISliceFilter;
import eu.solven.adhoc.filter.optimizer.IFilterOptimizer;
import eu.solven.adhoc.measure.sum.EmptyAggregation;
import eu.solven.adhoc.options.StandardQueryOptions;
import eu.solven.adhoc.query.cube.IGroupBy;
import eu.solven.adhoc.query.groupby.GroupByColumns;
import eu.solven.adhoc.query.table.FilteredAggregator;
import eu.solven.adhoc.query.table.TableQueryV3;
import eu.solven.adhoc.query.table.TableQueryV4;
import lombok.experimental.UtilityClass;

/**
 * Merges a {@link Set} of {@link TableQueryV4} into a single covering {@link TableQueryV4}, suitable for
 * {@link StandardQueryOptions#DRILLTHROUGH}.
 *
 * <p>
 * The merge produces a single query whose:
 * <ul>
 * <li>{@code filter} is the {@code OR} of every input WHERE filter (rows matching any input are returned),</li>
 * <li>{@code groupBy} is the non-ambiguous union of every input groupBy (a single {@link IGroupBy} carrying every
 * column requested by any input — see {@link GroupByColumns#mergeNonAmbiguous}),</li>
 * <li>aggregator set is the deduplicated union of every input {@link FilteredAggregator}, with indexes reassigned so
 * that name conflicts (same {@link eu.solven.adhoc.measure.model.Aggregator} name with distinct per-aggregator
 * {@code FILTER}s) become unique aliases (e.g. {@code k1}, {@code k1_1}, {@code k1_2}).</li>
 * </ul>
 *
 * <p>
 * The result is guaranteed to produce, when executed, one row per slice of the merged groupBy with all aggregators
 * populated as columns. This is the foundation of the DRILLTHROUGH path: each DB row maps to one user-visible tabular
 * entry without any cube-level measure transformation.
 *
 * @author Benoit Lacelle
 */
@UtilityClass
public class TableQueryV4Merger {

	/**
	 * Merge the given {@link TableQueryV4}s into a single covering {@link TableQueryV4}.
	 *
	 * @param queries
	 *            the set of {@link TableQueryV4} to merge. Must not be empty.
	 * @param filterOptimizer
	 *            optimizer used to simplify the {@code OR}-combined filter.
	 * @return a single {@link TableQueryV4} covering every input.
	 * @throws IllegalArgumentException
	 *             if {@code queries} is empty.
	 */
	public static TableQueryV4 merge(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		if (queries.isEmpty()) {
			throw new IllegalArgumentException("Cannot merge an empty set of TableQueryV4");
		}
		TableQueryV4 first = queries.iterator().next();
		if (queries.size() == 1) {
			return first;
		}

		IGroupBy mergedGroupBy = mergeGroupBy(queries);
		ISliceFilter mergedFilter = mergeFilter(queries, filterOptimizer);
		Set<FilteredAggregator> mergedAggregators = mergeAggregators(queries);

		return TableQueryV4.builder()
				.filter(mergedFilter)
				.groupByToAggregators(mergedGroupBy, mergedAggregators)
				.customMarker(first.getCustomMarker())
				.topClause(first.getTopClause())
				.options(first.getOptions())
				.build();
	}

	/**
	 * Variant of {@link #merge(Set, IFilterOptimizer)} tailored for {@link StandardQueryOptions#DRILLTHROUGH}: when
	 * several {@link FilteredAggregator}s share the same {@link eu.solven.adhoc.measure.model.Aggregator} name (e.g. an
	 * unfiltered {@code k1} alongside a {@code k1 FILTER(a==a1)} inducer generated by a {@link Shiftor}-like measure),
	 * the result keeps a <b>single</b> aggregator per name — preferring the most permissive (MATCH_ALL) filter, falling
	 * back to the first-seen one.
	 *
	 * <p>
	 * Rationale: DRILLTHROUGH bypasses cube-level measure transformations and surfaces table-side aggregator columns
	 * verbatim. The {@code _N}-indexed aliases ({@code k1_1}, {@code k1_2}, …) re-introduced by the merger to keep name
	 * conflicts unique in a regular execution are pure {@link TableQueryV4} internals and should not leak into the
	 * user-visible DRILLTHROUGH output.
	 */
	public static TableQueryV3 mergeForDrillthrough(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		TableQueryV4 merged = merge(queries, filterOptimizer);
		// Empty aggregators are slice-materialization aids (e.g. Shiftor's whereToReadForWrite) — they carry no
		// payload and would surface as a useless `empty` column in the DRILLTHROUGH output. Drop them before dedup.
		Set<FilteredAggregator> realAggregators = merged.getAggregators()
				.stream()
				.filter(fa -> !EmptyAggregation.isEmpty(fa.getAggregator()))
				.collect(ImmutableSet.toImmutableSet());
		Set<FilteredAggregator> dedupedByName = dedupeByAggregatorName(realAggregators);
		// Widen the merged WHERE filter to capture every (V4.WHERE AND fa.FILTER) pair — the row-inclusion
		// condition each (input V4, per-aggregator FILTER) originally carried — then OR them. Without this, a
		// V4 with WHERE=matchAll and two FILTERs `a=a1` and `a=a2` would widen row inclusion to "all rows"
		// instead of `a=a1 OR a=a2`. The widened WHERE then naturally exposes its filter columns to
		// `addFilteredColumnsToGroupBy`, so the helper keeps its single-arg signature.
		ISliceFilter rowInclusionFilter = computeRowInclusionFilter(queries, filterOptimizer);
		TableQueryV4 mergedWithFilter = merged.toBuilder().filter(rowInclusionFilter).build();
		IGroupBy enrichedGroupBy = addFilteredColumnsToGroupBy(mergedWithFilter);

		// DRILLTHROUGH does not benefit from V4's per-step partitioning of (groupBy × aggregators): there is no
		// GROUP BY at execution time, every row flows through with the union of aggregator columns. Returning a
		// V3 makes the contract explicit — single groupBy, single aggregator set — and saves the downstream layers
		// (JOOQ raw-rows query factory, InMemoryTable) from a pointless V4-to-V3 conversion. Aggregators are kept
		// verbatim: `streamRows` emits one record per DB row and never invokes the aggregation function, so there
		// is no need to rewrite to CoalesceAggregation, and the per-aggregator FILTER is preserved (the row-
		// streaming layer applies it per-row to populate the alias column with null when the FILTER does not match).
		return TableQueryV3.builder()
				.filter(rowInclusionFilter)
				.groupBy(enrichedGroupBy)
				.aggregators(ImmutableSet.copyOf(dedupedByName))
				.customMarker(merged.getCustomMarker())
				.topClause(merged.getTopClause())
				.options(merged.getOptions())
				.build();
	}

	/**
	 * @return the row-inclusion filter for DRILLTHROUGH: {@code OR over (V4, fa)} of {@code AND(V4.WHERE, fa.FILTER)}.
	 *         A row passes iff it satisfied at least one {@code (V4, aggregator)} pair's effective filter in the
	 *         original execution — preserving exactly the rows that any input was going to look at.
	 *
	 *         <p>
	 *         Empty aggregators are EXCLUDED from this computation: they exist only as slice-materialization aids (e.g.
	 *         Shiftor's {@code whereToReadForWrite}) and would otherwise contribute their {@code MATCH_ALL} FILTER to
	 *         the {@code OR}, collapsing it to {@code MATCH_ALL} and erasing the row-inclusion info from every other
	 *         input. DRILLTHROUGH does not use the empty aggregator's slice-materialization effect (the row-streaming
	 *         path emits one record per DB row regardless of the empty marker), so dropping it here is sound.
	 */
	protected ISliceFilter computeRowInclusionFilter(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		List<ISliceFilter> effectiveFilters = queries.stream().flatMap(q -> {
			ISliceFilter where = q.getFilter();
			List<FilteredAggregator> realAggregators =
					q.getAggregators().stream().filter(fa -> !EmptyAggregation.isEmpty(fa.getAggregator())).toList();
			if (realAggregators.isEmpty()) {
				// V4 with no real aggregator (e.g. all-empty V4): contributes its WHERE as-is — that WHERE is
				// the only row-inclusion signal it carries.
				return java.util.stream.Stream.of(where);
			}
			return realAggregators.stream()
					.map(fa -> FilterBuilder.and(where, fa.getFilter()).optimize(filterOptimizer));
		}).toList();
		return FilterBuilder.or(effectiveFilters).optimize(filterOptimizer);
	}

	/**
	 * @return an {@link IGroupBy} extending {@code merged}'s groupBy with every column referenced by the merged WHERE
	 *         filter or by any per-aggregator {@code FILTER}, deduplicated. Rationale: in DRILLTHROUGH the user wants
	 *         to see, on every output row, every column that participated in the query's resolution — including columns
	 *         that were only used to filter (and would otherwise be invisible). The caller is expected to pass the
	 *         post-{@code computeRowInclusionFilter} merged V4 so the row-inclusion columns are visible on
	 *         {@code merged.getFilter()}.
	 */
	protected IGroupBy addFilteredColumnsToGroupBy(TableQueryV4 merged) {
		IGroupBy currentGroupBy = merged.getGroupBys().iterator().next();
		Set<String> alreadyGrouped = currentGroupBy.getSortedColumns();

		ImmutableSet.Builder<String> filterColumnsBuilder = ImmutableSet.builder();
		filterColumnsBuilder.addAll(FilterHelpers.getFilteredColumns(merged.getFilter()));
		merged.getAggregators()
				.forEach(fa -> filterColumnsBuilder.addAll(FilterHelpers.getFilteredColumns(fa.getFilter())));
		Set<String> filterColumns = filterColumnsBuilder.build();

		Set<String> missing =
				filterColumns.stream().filter(c -> !alreadyGrouped.contains(c)).collect(ImmutableSet.toImmutableSet());
		if (missing.isEmpty()) {
			return currentGroupBy;
		}

		return GroupByColumns.builder()
				.columns(currentGroupBy.getColumns())
				.columns(missing.stream().map(ReferencedColumn::ref).toList())
				.build();
	}

	/**
	 * @return a deduplicated {@link Set} where each {@link eu.solven.adhoc.measure.model.Aggregator} name appears at
	 *         most once. Among candidates with the same Aggregator name, the one with {@code MATCH_ALL} filter wins;
	 *         otherwise the first-seen entry wins.
	 */
	protected Set<FilteredAggregator> dedupeByAggregatorName(Set<FilteredAggregator> aggregators) {
		Map<String, FilteredAggregator> nameToAggregator = new LinkedHashMap<>();
		aggregators.forEach(fa -> {
			String name = fa.getAggregator().getName();
			FilteredAggregator current = nameToAggregator.get(name);
			if (current == null || prefersIncoming(current, fa)) {
				// Reset to index=0 so the alias collapses back to the bare aggregator name (no `_N` suffix).
				nameToAggregator.put(name, fa.withIndex(0));
			}
		});
		return ImmutableSet.copyOf(nameToAggregator.values());
	}

	/**
	 * @return {@code true} when {@code incoming} should replace {@code current} in the dedup map: the MATCH_ALL filter
	 *         is preferred over any narrower filter.
	 */
	protected boolean prefersIncoming(FilteredAggregator current, FilteredAggregator incoming) {
		return !ISliceFilter.MATCH_ALL.equals(current.getFilter())
				&& ISliceFilter.MATCH_ALL.equals(incoming.getFilter());
	}

	/**
	 * @return the non-ambiguous union of every input groupBy, as a single {@link IGroupBy}.
	 */
	protected IGroupBy mergeGroupBy(Set<TableQueryV4> queries) {
		Set<IGroupBy> allGroupBys =
				queries.stream().flatMap(q -> q.getGroupBys().stream()).collect(ImmutableSet.toImmutableSet());
		return GroupByColumns.mergeNonAmbiguous(allGroupBys);
	}

	/**
	 * @return the {@code OR}-combination of every input WHERE filter, optimized.
	 */
	protected ISliceFilter mergeFilter(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		List<ISliceFilter> filters = queries.stream().map(TableQueryV4::getFilter).toList();
		return FilterBuilder.or(filters).optimize(filterOptimizer);
	}

	/**
	 * Collects every {@link FilteredAggregator} across the inputs, normalizes their indexes to {@code 0}, deduplicates
	 * by {@code (aggregator, filter)}, then re-indexes name conflicts so each aggregator carries a unique alias.
	 *
	 * @return the deduplicated and re-indexed aggregator set.
	 */
	protected Set<FilteredAggregator> mergeAggregators(Set<TableQueryV4> queries) {
		List<FilteredAggregator> normalized = queries.stream()
				.flatMap(q -> q.getAggregators().stream())
				.map(fa -> fa.withIndex(0))
				.distinct()
				.toList();

		AtomicLongMap<String> nameToNextIndex = AtomicLongMap.create();
		return normalized.stream().map(fa -> {
			long i = nameToNextIndex.getAndIncrement(fa.getAggregator().getName());
			return fa.withIndex(i);
		}).collect(ImmutableSet.toImmutableSet());
	}

}
