/**
 * The MIT License
 * Copyright (c) 2026 Benoit Chatain Lacelle - SOLVEN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.solven.adhoc.engine.tabular.optimizer;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.google.common.collect.ImmutableSet;
import com.google.common.util.concurrent.AtomicLongMap;

import eu.solven.adhoc.column.ReferencedColumn;
import eu.solven.adhoc.filter.FilterBuilder;
import eu.solven.adhoc.filter.FilterHelpers;
import eu.solven.adhoc.filter.ISliceFilter;
import eu.solven.adhoc.filter.optimizer.IFilterOptimizer;
import eu.solven.adhoc.measure.sum.CoalesceAggregation;
import eu.solven.adhoc.options.StandardQueryOptions;
import eu.solven.adhoc.query.cube.IGroupBy;
import eu.solven.adhoc.query.groupby.GroupByColumns;
import eu.solven.adhoc.query.table.FilteredAggregator;
import eu.solven.adhoc.query.table.TableQueryV4;
import lombok.experimental.UtilityClass;

/**
 * Merges a {@link Set} of {@link TableQueryV4} into a single covering {@link TableQueryV4}, suitable for
 * {@link StandardQueryOptions#DRILLTHROUGH}.
 *
 * <p>
 * The merge produces a single query whose:
 * <ul>
 * <li>{@code filter} is the {@code OR} of every input WHERE filter (rows matching any input are returned),</li>
 * <li>{@code groupBy} is the non-ambiguous union of every input groupBy (a single {@link IGroupBy} carrying every
 * column requested by any input — see {@link GroupByColumns#mergeNonAmbiguous}),</li>
 * <li>aggregator set is the deduplicated union of every input {@link FilteredAggregator}, with indexes reassigned so
 * that name conflicts (same {@link eu.solven.adhoc.measure.model.Aggregator} name with distinct per-aggregator
 * {@code FILTER}s) become unique aliases (e.g. {@code k1}, {@code k1_1}, {@code k1_2}).</li>
 * </ul>
 *
 * <p>
 * The result is guaranteed to produce, when executed, one row per slice of the merged groupBy with all aggregators
 * populated as columns. This is the foundation of the DRILLTHROUGH path: each DB row maps to one user-visible tabular
 * entry without any cube-level measure transformation.
 *
 * @author Benoit Lacelle
 */
@UtilityClass
public class TableQueryV4Merger {

	/**
	 * Merge the given {@link TableQueryV4}s into a single covering {@link TableQueryV4}.
	 *
	 * @param queries
	 *            the set of {@link TableQueryV4} to merge. Must not be empty.
	 * @param filterOptimizer
	 *            optimizer used to simplify the {@code OR}-combined filter.
	 * @return a single {@link TableQueryV4} covering every input.
	 * @throws IllegalArgumentException
	 *             if {@code queries} is empty.
	 */
	public static TableQueryV4 merge(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		if (queries.isEmpty()) {
			throw new IllegalArgumentException("Cannot merge an empty set of TableQueryV4");
		}
		TableQueryV4 first = queries.iterator().next();
		if (queries.size() == 1) {
			return first;
		}

		IGroupBy mergedGroupBy = mergeGroupBy(queries);
		ISliceFilter mergedFilter = mergeFilter(queries, filterOptimizer);
		Set<FilteredAggregator> mergedAggregators = mergeAggregators(queries);

		return TableQueryV4.builder()
				.filter(mergedFilter)
				.groupByToAggregators(mergedGroupBy, mergedAggregators)
				.customMarker(first.getCustomMarker())
				.topClause(first.getTopClause())
				.options(first.getOptions())
				.build();
	}

	/**
	 * Variant of {@link #merge(Set, IFilterOptimizer)} tailored for {@link StandardQueryOptions#DRILLTHROUGH}: when
	 * several {@link FilteredAggregator}s share the same {@link eu.solven.adhoc.measure.model.Aggregator} name (e.g. an
	 * unfiltered {@code k1} alongside a {@code k1 FILTER(a==a1)} inducer generated by a {@link Shiftor}-like measure),
	 * the result keeps a <b>single</b> aggregator per name — preferring the most permissive (MATCH_ALL) filter, falling
	 * back to the first-seen one.
	 *
	 * <p>
	 * Rationale: DRILLTHROUGH bypasses cube-level measure transformations and surfaces table-side aggregator columns
	 * verbatim. The {@code _N}-indexed aliases ({@code k1_1}, {@code k1_2}, …) re-introduced by the merger to keep name
	 * conflicts unique in a regular execution are pure {@link TableQueryV4} internals and should not leak into the
	 * user-visible DRILLTHROUGH output.
	 */
	public static TableQueryV4 mergeForDrillthrough(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		TableQueryV4 merged = merge(queries, filterOptimizer);
		Set<FilteredAggregator> dedupedByName = dedupeByAggregatorName(merged.getAggregators());
		Set<FilteredAggregator> rowPreserving = rewriteToRowPreserving(dedupedByName);
		IGroupBy enrichedGroupBy = addFilteredColumnsToGroupBy(merged);

		return merged.toBuilder()
				.clearGroupByToAggregators()
				.groupByToAggregators(enrichedGroupBy, rowPreserving)
				.build();
	}

	/**
	 * Rewrite every aggregator to use {@link CoalesceAggregation} so the table layer never collapses figures: each
	 * source row's value flows through unchanged. Critical for measures backed by an
	 * {@link eu.solven.adhoc.measure.aggregation.carrier.IAggregationCarrier} (e.g. Rank, percentile sketches), where
	 * applying the natural aggregation at the row level is meaningless or outright errors. Also makes
	 * {@code Sum}/{@code Avg} measures behave intuitively in DRILLTHROUGH (each row exposes its raw contribution, not a
	 * per-slice sum).
	 *
	 * <p>
	 * The aggregator name (alias) is preserved, so the user-visible column key is unchanged.
	 */
	protected Set<FilteredAggregator> rewriteToRowPreserving(Set<FilteredAggregator> aggregators) {
		return aggregators.stream()
				.map(fa -> fa.toBuilder()
						.aggregator(fa.getAggregator().toBuilder().aggregationKey(CoalesceAggregation.KEY).build())
						.build())
				.collect(ImmutableSet.toImmutableSet());
	}

	/**
	 * @return an {@link IGroupBy} extending {@code merged}'s groupBy with every column referenced by the merged WHERE
	 *         filter or by any per-aggregator {@code FILTER} clause, deduplicated. Rationale: in DRILLTHROUGH the user
	 *         wants to see, on every output row, every column that participated in the query's resolution — including
	 *         columns that were only used to filter (and would otherwise be invisible).
	 */
	protected IGroupBy addFilteredColumnsToGroupBy(TableQueryV4 merged) {
		IGroupBy currentGroupBy = merged.getGroupBys().iterator().next();
		Set<String> alreadyGrouped = currentGroupBy.getSortedColumns();

		ImmutableSet.Builder<String> filterColumnsBuilder = ImmutableSet.builder();
		filterColumnsBuilder.addAll(FilterHelpers.getFilteredColumns(merged.getFilter()));
		merged.getAggregators()
				.forEach(fa -> filterColumnsBuilder.addAll(FilterHelpers.getFilteredColumns(fa.getFilter())));
		Set<String> filterColumns = filterColumnsBuilder.build();

		Set<String> missing =
				filterColumns.stream().filter(c -> !alreadyGrouped.contains(c)).collect(ImmutableSet.toImmutableSet());
		if (missing.isEmpty()) {
			return currentGroupBy;
		}

		return GroupByColumns.builder()
				.columns(currentGroupBy.getColumns())
				.columns(missing.stream().map(ReferencedColumn::ref).toList())
				.build();
	}

	/**
	 * @return a deduplicated {@link Set} where each {@link eu.solven.adhoc.measure.model.Aggregator} name appears at
	 *         most once. Among candidates with the same Aggregator name, the one with {@code MATCH_ALL} filter wins;
	 *         otherwise the first-seen entry wins.
	 */
	protected Set<FilteredAggregator> dedupeByAggregatorName(Set<FilteredAggregator> aggregators) {
		Map<String, FilteredAggregator> nameToAggregator = new LinkedHashMap<>();
		aggregators.forEach(fa -> {
			String name = fa.getAggregator().getName();
			FilteredAggregator current = nameToAggregator.get(name);
			if (current == null || prefersIncoming(current, fa)) {
				// Reset to index=0 so the alias collapses back to the bare aggregator name (no `_N` suffix).
				nameToAggregator.put(name, fa.withIndex(0));
			}
		});
		return ImmutableSet.copyOf(nameToAggregator.values());
	}

	/**
	 * @return {@code true} when {@code incoming} should replace {@code current} in the dedup map: the MATCH_ALL filter
	 *         is preferred over any narrower filter.
	 */
	protected boolean prefersIncoming(FilteredAggregator current, FilteredAggregator incoming) {
		return !ISliceFilter.MATCH_ALL.equals(current.getFilter())
				&& ISliceFilter.MATCH_ALL.equals(incoming.getFilter());
	}

	/**
	 * @return the non-ambiguous union of every input groupBy, as a single {@link IGroupBy}.
	 */
	protected IGroupBy mergeGroupBy(Set<TableQueryV4> queries) {
		Set<IGroupBy> allGroupBys =
				queries.stream().flatMap(q -> q.getGroupBys().stream()).collect(ImmutableSet.toImmutableSet());
		return GroupByColumns.mergeNonAmbiguous(allGroupBys);
	}

	/**
	 * @return the {@code OR}-combination of every input WHERE filter, optimized.
	 */
	protected ISliceFilter mergeFilter(Set<TableQueryV4> queries, IFilterOptimizer filterOptimizer) {
		List<ISliceFilter> filters = queries.stream().map(TableQueryV4::getFilter).toList();
		return FilterBuilder.or(filters).optimize(filterOptimizer);
	}

	/**
	 * Collects every {@link FilteredAggregator} across the inputs, normalizes their indexes to {@code 0}, deduplicates
	 * by {@code (aggregator, filter)}, then re-indexes name conflicts so each aggregator carries a unique alias.
	 *
	 * @return the deduplicated and re-indexed aggregator set.
	 */
	protected Set<FilteredAggregator> mergeAggregators(Set<TableQueryV4> queries) {
		List<FilteredAggregator> normalized = queries.stream()
				.flatMap(q -> q.getAggregators().stream())
				.map(fa -> fa.withIndex(0))
				.distinct()
				.toList();

		AtomicLongMap<String> nameToNextIndex = AtomicLongMap.create();
		return normalized.stream().map(fa -> {
			long i = nameToNextIndex.getAndIncrement(fa.getAggregator().getName());
			return fa.withIndex(i);
		}).collect(ImmutableSet.toImmutableSet());
	}

}
