#!/usr/bin/env perl
# Detect Stepdown Rule violations in Java source files.
# A violation: method M calls method C declared *above* M in the same class.
#
# Usage:  perl scripts/check-stepdown.pl [file|dir ...]
#         Directories are searched recursively for *.java (test paths skipped).
# Exit:   0 = clean, 1 = violations found.

use strict;
use warnings;
use File::Find;

# Java keywords that look like calls but aren't.
my @KEYWORDS = qw(if for while switch catch return throw new instanceof synchronized assert);
# Methods inherited from Object or generated by Lombok — not subject to Stepdown ordering.
my @SKIP = qw(toString hashCode equals compareTo clone build builder toBuilder add get put);
my %KW   = map { $_ => 1 } (@KEYWORDS, @SKIP);

# A method declaration with an empty or semicolon-only body is abstract — skip as callee.
# We track abstract methods separately so they don't trigger violations when called above a caller.
my %abstract;

my @files = @ARGV ? @ARGV : ('.');
my @java;
for my $arg (@files) {
    if (-f $arg) { push @java, $arg }
    else { find(sub { push @java, $File::Find::name if /\.java$/ && !/\/test\// }, $arg) }
}

my $total = 0;
for my $file (sort @java) {
    open my $fh, '<', $file or die "Cannot open $file: $!";
    my (%decl_line, %abstract, @order, $depth, $cur_name, $cur_line, %seen);
    $depth = 0;

    while (my $line = <$fh>) {
        my $code = $line =~ s|//.*||r;     # strip single-line comments

        # Collect method declarations at class-body depth (depth == 1).
        if ($depth == 1 && $line =~ /^\s+(?:(?:public|protected|private|static|final|synchronized|abstract|default)\s+)*[\w<>\[\]?,.\s]+\b(\w+)\s*\(/) {
            my $name = $1;
            unless (exists $decl_line{$name}) {
                $decl_line{$name} = $.;
                push @order, $name;
                # Abstract if the declaration line ends with ';' (no body).
                $abstract{$name} = 1 if $line =~ /\)\s*(?:throws[^{;]+)?;/;
            }
            $cur_name = $name;
            $cur_line = $.;
        }

        $depth += () = $code =~ /\{/g;
        $depth -= () = $code =~ /\}/g;

        # Scan for calls inside method bodies (depth >= 2).
        if ($depth >= 2 && $cur_name) {
            while ($code =~ /\b(\w+)\s*\(/g) {
                my $callee = $1;
                next if $KW{$callee} || $callee eq $cur_name;
                # Skip constructor calls (`new Foo(`) — constructors are not subject to Stepdown ordering.
                # Skip qualified calls (`Foo.bar(` or `obj.bar(`) — only unqualified calls to sibling methods matter.
                my $pre = substr($code, 0, $-[0]);
                next if $pre =~ /\bnew\s+$/;
                next if $pre =~ /\.\s*$/;
                next unless exists $decl_line{$callee};
                next if $abstract{$callee};   # abstract methods are entry-point contracts, not callees
                next if $decl_line{$callee} >= $cur_line;   # declared below — OK
                my $key = "$cur_name->$callee";
                next if $seen{$key}++;
                print "$file:$cur_line: '$cur_name' calls '$callee' declared above it at line $decl_line{$callee}\n";
                $total++;
            }
        }
    }
    close $fh;
}

print "\n$total Stepdown violation(s) found.\n" if $total;
exit($total ? 1 : 0);
