flowchart LR
    adhoc_cell["adhoc-cell"]
    adhoc_cube["adhoc-cube"]
    adhoc_dataframe["adhoc-dataframe"]
    adhoc_encoding["adhoc-encoding"]
    adhoc_filters["adhoc-filters"]
    adhoc_fsst["adhoc-fsst"]
    adhoc_measures["adhoc-measures"]
    adhoc_recipes["adhoc-recipes"]
    adhoc_table["adhoc-table"]
    pivotable_bom["pivotable-bom"]
    pivotable_infra["pivotable-infra"]
    pivotable_js["pivotable-js"]
    pivotable_mcp["pivotable-mcp"]
    pivotable_mcp_webflux["pivotable-mcp-webflux"]
    pivotable_mcp_webmvc["pivotable-mcp-webmvc"]
    pivotable_model["pivotable-model"]
    pivotable_server["pivotable-server"]
    pivotable_server_core["pivotable-server-core"]
    pivotable_server_oauth2["pivotable-server-oauth2"]
    pivotable_server_webflux["pivotable-server-webflux"]
    pivotable_server_webmvc["pivotable-server-webmvc"]

    subgraph aggregator-adhoc
        adhoc_atoti["adhoc-atoti"]
        adhoc_bom["adhoc-bom"]
        adhoc_calcite["adhoc-calcite"]
        adhoc_engine["adhoc-engine"]
        adhoc_experimental["adhoc-experimental"]
        adhoc_libraries["adhoc-libraries"]
        adhoc_model["adhoc-model"]
        adhoc_spring["adhoc-spring"]
        pivotable["pivotable"]
    end

    adhoc_atoti --> adhoc_recipes
    adhoc_calcite --> adhoc_cube
    adhoc_cell --> adhoc_encoding
    adhoc_cell --> adhoc_filters
    adhoc_cube --> adhoc_dataframe
    adhoc_cube --> adhoc_encoding
    adhoc_cube --> adhoc_model
    adhoc_cube --> adhoc_table
    adhoc_dataframe --> adhoc_cell
    adhoc_dataframe --> adhoc_encoding
    adhoc_dataframe --> adhoc_measures
    adhoc_dataframe --> adhoc_model
    adhoc_encoding --> adhoc_fsst
    adhoc_encoding --> adhoc_model
    adhoc_experimental --> adhoc_cube
    adhoc_filters --> adhoc_model
    adhoc_measures --> adhoc_cell
    adhoc_recipes --> adhoc_cube
    adhoc_spring --> adhoc_cube
    adhoc_table --> adhoc_cell
    adhoc_table --> adhoc_dataframe
    adhoc_table --> adhoc_encoding
    adhoc_table --> adhoc_filters
    adhoc_table --> adhoc_measures
    adhoc_table --> adhoc_model
    pivotable_mcp --> pivotable_server_core
    pivotable_mcp_webflux --> pivotable_mcp
    pivotable_mcp_webmvc --> pivotable_mcp
    pivotable_model --> adhoc_filters
    pivotable_server --> pivotable_js
    pivotable_server --> pivotable_server_core
    pivotable_server --> pivotable_server_oauth2
    pivotable_server_core --> adhoc_recipes
    pivotable_server_core --> pivotable_infra
    pivotable_server_core --> pivotable_model
    pivotable_server_oauth2 --> pivotable_infra
    pivotable_server_oauth2 --> pivotable_model
    pivotable_server_webflux --> adhoc_experimental
    pivotable_server_webflux --> pivotable_mcp_webflux
    pivotable_server_webflux --> pivotable_server
    pivotable_server_webmvc --> adhoc_experimental
    pivotable_server_webmvc --> pivotable_mcp_webmvc
    pivotable_server_webmvc --> pivotable_server
