/**
 * The MIT License
 * Copyright (c) 2025 Benoit Chatain Lacelle - SOLVEN
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package eu.solven.adhoc.util.mermaid;

import java.io.IOException;
import java.nio.file.Path;

import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * Focused unit test for {@link ClassHierarchyAsJavaParserMermaid} using minimal fixture classes.
 *
 * <p>
 * The fixture lives in {@code src/test/java/.../testdata/} and contains:
 * <ul>
 * <li>{@code SimpleRoot} — two fields: one with {@code @Default}, one without.</li>
 * <li>{@code ISimpleEngine} / {@code SimpleEngine} — engine interface + its sole concrete default.</li>
 * <li>{@code ISimpleWidget} / {@code SimpleWidgetA} / {@code SimpleWidgetB} — widget interface + two impls.</li>
 * </ul>
 *
 * <p>
 * Maven sets the working directory to the module root, so {@code Path.of("src/test/java/...")} resolves correctly. See
 * https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#workingDirectory
 */
// @Disabled("WIP")
public class TestClassHierarchyAsJavaParserMermaidSimple {

	/** Source root scoped to just the fixture package to keep the test fast and isolated. */
	private static final Path FIXTURE_ROOT = Path.of("src/test/java/eu/solven/adhoc/util/mermaid/testdata");

	private ClassHierarchyAsJavaParserMermaid analyzer() {
		return ClassHierarchyAsJavaParserMermaid.builder().sourceRoot(FIXTURE_ROOT).build();
	}

	@Test
	public void testMermaidOutput() throws IOException {
		ClassHierarchyAsJavaParserMermaid analyzer = analyzer();
		String diagram = analyzer.toMermaid(analyzer.buildGraph("SimpleRoot"));

		Assertions.assertThat(diagram)
				.isEqualTo(
						"""
								%% AUTO-GENERATED by ClassHierarchyAsJavaParserMermaid — do not edit by hand. Re-run the generator to refresh.
								classDiagram
								    direction TB

								    %% ─── Interfaces ────────────────────────────────────────────────
								    class ISimpleWidget {
								    }

								    %% ─── Concrete classes ──────────────────────────────────────────
								    class SimpleEngine {
								        ISubEngine subEngine
								    }
								    class SimpleRoot {
								        ISimpleEngine engine
								        ISimpleWidget widget
								    }
								    class SimpleSubEngine {
								    }
								    class SimpleWidgetA {
								    }
								    class SimpleWidgetB {
								    }

								    %% ─── Implements / Extends ──────────────────────────────────────
								    ISimpleWidget <|.. SimpleWidgetA
								    ISimpleWidget <|.. SimpleWidgetB

								    %% ─── Composition ───────────────────────────────────────────────
								    SimpleRoot *-- SimpleEngine : engine
								    SimpleEngine *-- SimpleSubEngine : subEngine
								    SimpleRoot *-- ISimpleWidget : widget
												""");
	}
}
