# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Adhoc Spotless

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
	- name: Download dependencies
	  run: mvn dependency:collect --file pom.xml --batch-mode
	- name: Package skipping tests
	  # This is useful not to clutter the package command with download logs
	  # `mvn dependency` has issues with multi-modules
	  # run: mvn dependency:resolve dependency:resolve-plugins --batch-mode
	  run: mvn package -Pfast --file pom.xml --batch-mode
	- name: Java unit-tests
	  # Stick to `package` phase for consistency, and checking packaging is fine
	  run: mvn test -Dgroups=adhoc-benchmark --file pom.xml --batch-mode
