name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    # Package the server to serve API and JS
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - uses: actions/setup-node@v5
      with:
        node-version: lts/*
    - name: Install NPM dependencies
      working-directory: ./pivotable/js
      run: npm ci
    - name: Run ViTest tests
      working-directory: ./pivotable/js
      run: npm run unit_tests_ci
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: vitest-report
        path: pivotable/js/vitest-report/
        retention-days: 30
